
const swaggerAutogen = require('swagger-autogen')()

const outputFile = './swagger_output.json'
const endpointsFiles = ['./routes/index.js']


const doc = {
    info: {
        version: "1.0.0",
        title: "My API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:8080",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "Contacts",
            "description": "Endpoints"
        }
    ],
    definitions: {
        Contact: {
            "firstName": "john",
            "lastName": "doe",
            "email": "johndoe@swagger.com",
            "favoriteColor": "red",
            "birthday": "2023/1/27"
        },
        AddContact: {
            "firstName": "john",
            "lastName": "doe",
            "email": "johndoe@swagger.com",
            "favoriteColor": "red",
            "birthday": "2023/1/27"
        },
        contact_id: "63caeccb50a864c0afbdb910",
        delRes: {
            "acknowledged": true,
            "deletedCount": 1
        }
    }
}
swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    // eslint-disable-next-line global-require, import/extensions
    require('./app.js')
})